#!/bin/bash
# gen_embedded.sh - Generate C files with embedded userspace binaries
# Licensed under MIT License - URIX project.

BUILDDIR="${1:-build}"

# Dynamically populate PROGRAMS with files from BUILDDIR
PROGRAMS=()
for file in "$BUILDDIR"/*; do
    if [ -f "$file" ] && [[ "$file" != *.o ]]; then
        PROGRAMS+=("$(basename "$file")")
    fi
done

# Create the .c file
cat > embedded_programs.c << 'EOF'
/*
 * Auto-generated embedded userspace binaries
 * DO NOT EDIT - generated by gen_embedded.sh
 */

#include <stdint.h>
#include <embedded_programs.h>
#ifndef NULL
#define NULL ((void *)0)
#endif

EOF

# Create the .h file
cat > embedded_programs.h << 'EOF'
/*
 * Auto-generated embedded userspace binaries header
 * DO NOT EDIT - generated by gen_embedded.sh
 */

#ifndef EMBEDDED_PROGRAMS_H
#define EMBEDDED_PROGRAMS_H

#include <stdint.h>

EOF

# Function to convert binary to C array
bin_to_c_array() {
    local file="$1"
    local output="$2"
    
    # Try xxd first (cleanest output)
    if command -v xxd >/dev/null 2>&1; then
        xxd -i < "$file" >> "$output"
        return
    fi
    
    # Fall back to Python
    if command -v python3 >/dev/null 2>&1; then
        python3 -c "
import sys
with open('$file', 'rb') as f:
    data = f.read()
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_str = ', '.join(f'0x{b:02x}' for b in chunk)
        print(f'{hex_str},')
" >> "$output"
        return
    fi
    
    # Fall back to od with proper formatting
    od -An -tx1 -v "$file" | \
        sed 's/^ *//;s/  */ /g;s/ /, 0x/g;s/^/0x/;s/$/,/' | \
        sed 's/0x,//' >> "$output"
}

# Process each binary
for prog in "${PROGRAMS[@]}"; do
    if [ ! -f "$BUILDDIR/$prog" ]; then
        echo "Warning: $BUILDDIR/$prog not found"
        continue
    fi
    
    echo "Processing $prog..."
    
    size=$(stat -c%s "$BUILDDIR/$prog" 2>/dev/null || stat -f%z "$BUILDDIR/$prog")
    
    # Add extern declaration to header
    echo "extern uint8_t embedded_${prog}[];" >> embedded_programs.h
    echo "extern const uint64_t embedded_${prog}_size;" >> embedded_programs.h
    echo "" >> embedded_programs.h
    
    # Add array to C file
    echo "/* $prog - $size bytes */" >> embedded_programs.c
    echo "uint8_t embedded_${prog}[] = {" >> embedded_programs.c
    
    bin_to_c_array "$BUILDDIR/$prog" embedded_programs.c
    
    echo "};" >> embedded_programs.c
    echo "uint64_t const embedded_${prog}_size = sizeof(embedded_${prog});" >> embedded_programs.c
    echo "" >> embedded_programs.c
done

# Add lookup table to both files
cat >> embedded_programs.h << 'EOF'
typedef struct {
    char *name;
    uint8_t *data;
    uint64_t size;
} embedded_binary_t;

extern embedded_binary_t embedded_binaries[];
extern int embedded_binaries_count;

#endif /* EMBEDDED_PROGRAMS_H */
EOF

cat >> embedded_programs.c << 'EOF'

embedded_binary_t embedded_binaries[] = {
EOF

for prog in "${PROGRAMS[@]}"; do
    if [ -f "$BUILDDIR/$prog" ]; then
        echo "    {\"$prog\", embedded_${prog}, embedded_${prog}_size}," >> embedded_programs.c
    fi
done

cat >> embedded_programs.c << 'EOF'
    {NULL, NULL, 0}
};

int embedded_binaries_count = (sizeof(embedded_binaries) / sizeof(embedded_binary_t)) - 1;
EOF

echo ""
echo "Generated:"
echo "  - embedded_programs.c"
echo "  - embedded_programs.h"